# Generated by Django 5.2.5 on 2025-09-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(default='Jyotish Mallik', max_length=100)),
                ('file_type', models.CharField(default='png', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
