# Generated by Django 5.2.6 on 2025-09-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
