# Generated by Django 5.2.6 on 2025-09-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_uploadfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='insights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
