# Generated by Django 5.2.6 on 2025-09-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0004_alter_uploadfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded_by',
            field=models.CharField(default='Jyotish Mallik', max_length=100),
        ),
    ]
