# Generated by Django 5.2.6 on 2025-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0006_alter_uploadfile_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
