# Generated by Django 5.2.6 on 2025-09-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0008_remove_uploadfile_uploaded_by_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='file_name',
            new_name='req_file_name',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='file_type',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='req_file',
            field=models.FileField(blank=True, null=True, upload_to='req_docs/'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='req_file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='req_file_type',
            field=models.CharField(blank=True, default='application/octet-stream', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='rule_file',
            field=models.FileField(blank=True, null=True, upload_to='rule_docs/'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='rule_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='rule_file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='rule_file_type',
            field=models.CharField(blank=True, default='application/octet-stream', max_length=100, null=True),
        ),
    ]
