# Generated by Django 5.2.6 on 2025-09-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0009_rename_file_name_uploadfile_req_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='check_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
