# Generated by Django 5.2.6 on 2025-09-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0010_uploadfile_check_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='req_file_size',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='rule_file_size',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
