# Generated by Django 5.2.6 on 2025-09-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0011_alter_uploadfile_req_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='visual_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
